DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
    ID              SERIAL PRIMARY KEY,
    USERNAME        VARCHAR(254) NOT NULL UNIQUE,
    EMAIL           VARCHAR(254) NOT NULL UNIQUE,
    FIRSTNAME       VARCHAR(254) NOT NULL UNIQUE,
    LASTNAME        VARCHAR(254) NOT NULL UNIQUE,
    PHOTO           VARCHAR(254) NOT NULL UNIQUE DEFAULT 'avatar/default.jpg',
    IS_ADMIN        BOOLEAN DEFAULT FALSE,
    IS_STAFF        BOOLEAN DEFAULT FALSE,
    IS_SUPERUSER    BOOLEAN DEFAULT TRUE,
    CREATE_AT       TIMESTAMP NOT NULL
);